#!/bin/sh

# ensure ~/.fonts exists
if [ ! -d ~/.fonts ]; then
  mkdir ~/.fonts
fi

# create the pcf files
bdftopcf -o ~/.fonts/daisy.pcf daisy.bdf
bdftopcf -o ~/.fonts/daisy\ bold.pcf daisy\ bold.bdf

# install the fonts
mkfontdir ~/.fonts
mkfontscale ~/.fonts
xset +fp ~/.fonts
xset fp rehash
fc-cache
fc-cache -fv

